
print:
	@echo cli

run:
	#go-bindata -fs -nomemcopy -o main/server/assets.go -prefix "client/build/web/" client/build/web/...
	#go-bindata -fs -nomemcopy -o $(CODE_PATH)/assets.go -prefix "client/build/web/" assets/...
	go run main.go
	#go run $(CODE_PATH)/main.go





